version: "3.8"
services:
  usera:
    platform: linux/x86_64
    hostname: userA
    build: .
    ports:
      - "6788:6788"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    platform: linux/x86_64
    volumes:
      - data:/data/db

volumes:
  data:
