version: "3.8"
services:
  usera:
    platform: linux/x86_64
    hostname: userA
    env_file:
      - ./env/dbCredentials.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - USERNAME=userA
    ports:
      - "8081:6788"
    depends_on:
      - mysql

  userb:
    platform: linux/x86_64
    hostname: userB
    env_file:
      - ./env/dbCredentials.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - USERNAME=userB
    ports:
      - "8082:6788"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    platform: linux/x86_64
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
